### ISSUE TITLE
RSS/Atom support

### ISSUE THREAD

**Issue by guygregory** [azurecitadel/azurecitadel.github.io#1]
I think it'd be nice to syndicate this content via RSS/Atom. What do others think? Is there a preferred approach to accomplish this with Jekyll?

**Comment by richeney** [comment]
Maybe!: [https://github.com/jekyll/jekyll-feed](https://github.com/jekyll/jekyll-feed)

**Comment by guygregory** [comment]
Oooh, nice! I can see that the jekyll-feed module is enabled (and live), but it looks like it's only pulling old newsletters:

https://azurecitadel.github.io/atom.xml

Is there any way to configure the locations it indexes?

**Comment by richeney** [comment]
It is configured as per this:

https://github.com/jekyll/jekyll-feed

So we can’t auto index.  However, I have been thinking about resurrecting the posts.  Some of what I want to get out there does not fit into a workshop or lab.  I absolutely don’t want to do another Azure Weekly – we can point people towards those – but new content on Citadel (or elsewhere), and partner pertinent stuff could make sense.  I’ll have a think.

Which reader are you using btw?  I downloaded a free one from the Store – myFeed – which looks OK.

**Comment by guygregory** [comment]
Primarily, I use Netvibes.com to aggregate news and other useful feeds. I also use Microsoft Flow to alert me (via push notification) to new content when it's syndicated via RSS/Atom (e.g. Azure Announcements).

**Comment by richeney** [comment]
Ah, Flow is a nice idea.

**Comment by benc-uk** [comment]
Netvibes?! Whoa!
https://www.youtube.com/watch?v=031vKBPk5eA

I used to love Netvibes

**Comment by guygregory** [comment]
Hehe, I’ve been using Netvibes since forever, but never found anyone else who used it! I’m always open to suggestions on better ways to aggregate news and content, so let me know if you have any ideas, please let me know!

**Comment by benc-uk** [comment]
Done in new version of site
