### ISSUE TITLE
Ordering of items on summary page

### ISSUE THREAD

**Issue by markharrison** [azurecitadel/azurecitadel.github.io#16]
Ordering of items on summary pages (like Labs) is a bit random - in reverse published date order might be better.

**Comment by benc-uk** [comment]
It's totally random.

It also seems extremely non-trivial to fix (from a quick Google). It'll involve me pulling the Liquid templates apart

Definitely needs looking at

**Comment by benc-uk** [comment]
done! 1661e8192e342e61c115a2c9ece345424b3e7075
