### ISSUE TITLE
Docker [suggestion]

### ISSUE THREAD

**Issue by markharrison** [azurecitadel/azurecitadel.github.io#17]
Update guidance to offer Docker as an alternative (to me, i found it simpler to set up) way to do site generation / testing.

I used the following:
```docker run -e "JEKYLL_ENV=docker"  --label=jekyll --volume=%CD%:/srv/jekyll  -it -p 4000:4000 jekyll/jekyll jekyll serve  --config _config.yml,_config_local.yml --unpublished --future```

I then did a ```docker commit``` on the container to generate my own image ... by then using the new image it avoided downloading numerous packages each time I needed to generate / test.

**Comment by benc-uk** [comment]
Great solution. I'll add this to the docs when I get a chance
Just used this to get the site running locally, the WSL route no longer works and is such a massive hassle

I did have to fiddle with the drive sharing options in Docker, and also add the `--force_polling` option to get it to detect changes.

**Comment by richeney** [comment]
Ben, can I leave you to update the Contribute to Citadel guide?  I was thinking of rebuilding my machine at some point so I could test the guide at that point.

**Comment by benc-uk** [comment]
Yeah I'll update it when I get a chance, as it'll need some testing of the edge cases

**Comment by richeney** [comment]
I got Jekyll working against the repo (Minimal Mistakes version) and the Ubuntu 18.04 WSL distro on the store.  I think I had to install a couple of additional packages, but nothing major.  So I think we can stick with a non-Docker guide on the Citadel site.
