### ISSUE TITLE
Domain name / short URL

### ISSUE THREAD

**Issue by guygregory** [azurecitadel/azurecitadel.github.io#3]
Would it make sense to register a memorable domain name for this site?

Something like: mspdu.co.uk, msukpdu.com or ukpdu.com?

At the very least, we ought to reserve a short URL like http://aka.ms/ukpdu

**Comment by benc-uk** [comment]
We have [aka.ms/citadel](http://aka.ms/citadel) - so can we close?

**Comment by richeney** [comment]
Yes.  There are a few others against my name as well: aka.ms/

- azurecitadel and cloudcitadel
- azure-101
- citadelmarkdown
- citadelfeedback
