### ISSUE TITLE
Lab3 - Creating Multiple App Service Plans using Count Meta Parameter

### ISSUE THREAD

**Issue by agrajm** [azurecitadel/azurecitadel.github.io#70]
Hi @richeney 
Thanks for creating the awesome hands-on labs :)  
While trying out lab3 count meta parameter to create 3 different linux based free app service plans, I'm getting the following error:

`Error: Error creating/updating App Service Plan "plan-free-westus" (Resource Group "webapps"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Exceeded the limit of 1 free tier linux server farm per subscription." Details=[{"Message":"Exceeded the limit of 1 free tier linux server farm per subscription."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"11027","Message":"Exceeded the limit of 1 free tier linux server farm per subscription.","MessageTemplate":"Exceeded the limit of 1 free tier linux server farm per subscription.","Parameters":[]}}]`

Important part is **Exceeded the limit of 1 free tier linux server farm per subscription.**  
While the [limits ](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#app-service-limits) mention being able to create 10 free app service plans per region but my error message says otherwise for linux based free plans ! 

Have you been able to workaround this ?
I can confirm if I switch to Standard SKU it works well.

**Comment by richeney** [comment]
Cheers for the feedback!

Quick double check - the labs use Windows based web apps, but you modified to a linux based web app and hit the problem? And what kind of subscription do you have?  If you send your config as a GitHub Gist then I'll try it out on my Visual Studio and internal Microsoft subscriptions and see if it is a general limitation (!?) or a restriction based on your subscription offer.

**Comment by agrajm** [comment]
Hi @richeney 
Thanks for replying. 
AFAICT, the lab uses Linux based app service plans - see lab files - https://github.com/richeney/terraform-lab4/blob/master/webapps.tf#L22 

My Config with Linux based App Service Plans and Standard SKU that's working fine is present [here](https://github.com/agrajm/terraform-azure/blob/master/lab3/webapps.tf#L15-L29) If you change the SKU to Free it fails. 

Cheers,
Agraj

**Comment by mfarley281** [comment]
I also ran into this issue, following the exact directions in the lab (using a fully funded/paid (Pay As You Go) subscription).

Thanks to @agrajm for the workaround!

**Comment by richeney** [comment]
Thanks for bringing this back to my attention!  I need to rattle through the labs and refresh them for 0.12 - I have someone joining my team at Microsoft soon so that will help give the space and time for it - but in the meantime I have added a comment into the webapps.tf file based on the above.  At least that will save anyone else hunting around for the answer.

[https://github.com/richeney/terraform-lab4/blob/master/webapps.tf#L22](https://github.com/richeney/terraform-lab4/blob/master/webapps.tf#L22)
